backend:
  name: git-gateway
  repo: charlotte-urbanists/netlify-cms
  branch: main
local_backend: true

site_url: https://www.clturban.ist
media_folder: images
collections:
  - label: "Site Information"
    name: "site_info"
    files:
      - label: "Organization Values"
        name: "org_values"
        file: content/site_info/org_values.yml
        fields:
          - label: Values
            name: values
            label_singular: Value
            widget: list
            fields:
              - { label: Value, name: title, widget: string }
              - { label: Description, name: description, widget: text }
